import { MigrationInterface, QueryRunner } from "typeorm";

export class FreshSchema1786292912597 implements MigrationInterface {
    name = 'FreshSchema1786292912597'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."banner_targettype_enum" AS ENUM('DISPLAY_ONLY', 'NOVEL', 'BLOG')`);
        await queryRunner.query(`CREATE TABLE "banner" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderIndex" integer NOT NULL DEFAULT '0', "imageUrl" text, "targetType" "public"."banner_targettype_enum" NOT NULL DEFAULT 'NOVEL', "targetId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6d9e2570b3d85ba37b681cd4256" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_efa05d22002077f5c4705d4c21" ON "banner" ("orderIndex") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccaf837f12d98370d46f100bcb" ON "banner" ("targetType") `);
        await queryRunner.query(`CREATE INDEX "IDX_b77505eb57ce82f8d74bdfa17c" ON "banner" ("targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_10e84f71d01bc582941849169e" ON "banner" ("isActive") `);
        await queryRunner.query(`CREATE TABLE "comment_like" ("userId" uuid NOT NULL, "commentId" integer NOT NULL, CONSTRAINT "PK_5ddb528d11dfb6fdc09e623907b" PRIMARY KEY ("userId", "commentId"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(30) NOT NULL, "slug" character varying(50) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "UQ_b3aa10c29ea4e61a830362bd25a" UNIQUE ("slug"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3aa10c29ea4e61a830362bd25" ON "tags" ("slug") `);
        await queryRunner.query(`CREATE TABLE "library" ("userId" uuid NOT NULL, "novelId" uuid NOT NULL, "isHidden" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_81b84722c56c8d0519e50a6eed3" PRIMARY KEY ("userId", "novelId"))`);
        await queryRunner.query(`CREATE TABLE "reply_like" ("userId" uuid NOT NULL, "replyId" integer NOT NULL, CONSTRAINT "PK_add1794dac65bb08470de49fea4" PRIMARY KEY ("userId", "replyId"))`);
        await queryRunner.query(`CREATE TABLE "reply" ("id" SERIAL NOT NULL, "content" character varying(1500) NOT NULL, "userId" uuid NOT NULL, "likeCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "parentReplyId" integer, "rootCommentId" integer NOT NULL, "deletedAt" TIMESTAMP, CONSTRAINT "PK_94fa9017051b40a71e000a2aff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9886d6d04a19413a2f0aac5d7" ON "reply" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0af68fe0e599c7cc7f34699ad" ON "reply" ("parentReplyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9edaea29c2239e325a82f0b1e5" ON "reply" ("rootCommentId") `);
        await queryRunner.query(`CREATE TABLE "user_verification" ("id" SERIAL NOT NULL, "code" character varying(6) NOT NULL, "expiry" TIMESTAMP NOT NULL, "lastSentAt" TIMESTAMP, "attempts" integer NOT NULL DEFAULT '0', "userId" uuid NOT NULL, CONSTRAINT "REL_b98835ab0c83f27ff7c4c7de3d" UNIQUE ("userId"), CONSTRAINT "PK_679edeb6fcfcbc4c094573e27e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "volume" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100), "coverImage" text, "orderIndex" numeric(6,2) NOT NULL DEFAULT '1', "novelId" uuid NOT NULL, CONSTRAINT "PK_666025cd0c36727216bb7f2a680" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_32b8c8af0bba587b76864d0eee" ON "volume" ("novelId", "orderIndex") `);
        await queryRunner.query(`CREATE TABLE "chapter_publication" ("chapterId" uuid NOT NULL, "volumeId" uuid NOT NULL, "sortKey" numeric(12,4) NOT NULL DEFAULT '1000', "publishedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_78e86463cfafdcd4c32fe157548" PRIMARY KEY ("chapterId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_30b15da7bd56c635a402b59874" ON "chapter_publication" ("publishedAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7f6a9fe2a993304e22c38797a8" ON "chapter_publication" ("volumeId", "sortKey") `);
        await queryRunner.query(`CREATE TABLE "chapter_comment_like" ("userId" uuid NOT NULL, "commentId" integer NOT NULL, CONSTRAINT "PK_69b6c5d00a467fbbdd08723b6c5" PRIMARY KEY ("userId", "commentId"))`);
        await queryRunner.query(`CREATE TABLE "chapter_comment" ("id" SERIAL NOT NULL, "content" character varying(1500) NOT NULL, "imageUrl" text, "imageWidth" integer, "imageHeight" integer, "userId" uuid NOT NULL, "chapterId" uuid NOT NULL, "novelId" uuid NOT NULL, "rootCommentId" integer, "parentCommentId" integer, "likeCount" integer NOT NULL DEFAULT '0', "replyCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_acae709ef370113933331ffb065" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08b9872601c18975a5457b636a" ON "chapter_comment" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_19f8d1d4ca007b137ddc9f99ea" ON "chapter_comment" ("chapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd9c3b0fbfc235c2f1dabc4306" ON "chapter_comment" ("novelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cb7f1685fc47a53576c358b38" ON "chapter_comment" ("rootCommentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c3c884dd6793362d9b06e9b40" ON "chapter_comment" ("parentCommentId") `);
        await queryRunner.query(`CREATE TABLE "chapter" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200) NOT NULL, "content" text NOT NULL, "wordCount" integer NOT NULL DEFAULT '0', "novelId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "commentCount" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_af6f597ddea69fa331de40245c1" UNIQUE ("id", "novelId"), CONSTRAINT "PK_275bd1c62bed7dff839680614ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reading_stats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "novelId" uuid NOT NULL, "lastReadChapterId" uuid NOT NULL, "lastChapterProgress" double precision NOT NULL DEFAULT '0', "totalReadTime" integer NOT NULL DEFAULT '0', "lastReadAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fc8c5010383a1a1f16fa8266337" UNIQUE ("userId", "novelId"), CONSTRAINT "PK_de7cb05873405f5f38e25b6eefb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."personal_notification_type_enum" AS ENUM('new_chapter', 'comment_reply', 'comment_like', 'reply_reply', 'reply_like', 'follow', 'message')`);
        await queryRunner.query(`CREATE TYPE "public"."personal_notification_targettype_enum" AS ENUM('novel', 'chapter', 'comment', 'reply', 'user', 'conversation', 'url')`);
        await queryRunner.query(`CREATE TABLE "personal_notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "actorUserId" uuid, "type" "public"."personal_notification_type_enum" NOT NULL, "targetType" "public"."personal_notification_targettype_enum" NOT NULL, "targetId" character varying(255), "targetUrl" text, "aggregationKey" character varying(255), "actorCount" integer NOT NULL DEFAULT '1', "data" jsonb, "titleSnapshot" character varying(255), "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "lastActivityAt" TIMESTAMP NOT NULL DEFAULT now(), "lastPushedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_3fd876fbf02133b1bfaab0a818e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c52c9f6bd7af5281a6bfc5fde7" ON "personal_notification" ("aggregationKey") `);
        await queryRunner.query(`CREATE TYPE "public"."user_device_provider_enum" AS ENUM('expo', 'fcm', 'apns')`);
        await queryRunner.query(`CREATE TYPE "public"."user_device_platform_enum" AS ENUM('ios', 'android', 'web')`);
        await queryRunner.query(`CREATE TABLE "user_device" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "pushToken" text NOT NULL, "provider" "public"."user_device_provider_enum" NOT NULL DEFAULT 'expo', "platform" "public"."user_device_platform_enum" NOT NULL, "deviceId" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "lastSeenAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0232591a0b48e1eb92f3ec5d0d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bda1afb30d9e3e8fb30b1e90af" ON "user_device" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7bcbc5516c8217e27beec37ab5" ON "user_device" ("pushToken") `);
        await queryRunner.query(`CREATE TABLE "user_follow" ("followerId" uuid NOT NULL, "followingId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_66a94f05e54219c24338eba637c" PRIMARY KEY ("followerId", "followingId"))`);
        await queryRunner.query(`CREATE TABLE "user_block" ("blockerId" uuid NOT NULL, "blockedId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d6b2a9c90a8c5f0997c6548c725" PRIMARY KEY ("blockerId", "blockedId"))`);
        await queryRunner.query(`CREATE TABLE "password_reset" ("id" SERIAL NOT NULL, "codeHash" character varying(255) NOT NULL, "expiry" TIMESTAMP NOT NULL, "lastSentAt" TIMESTAMP, "attempts" integer NOT NULL DEFAULT '0', "userId" uuid NOT NULL, CONSTRAINT "REL_05baebe80e9f8fab8207eda250" UNIQUE ("userId"), CONSTRAINT "PK_8515e60a2cc41584fa4784f52ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_auth_provider_enum" AS ENUM('local', 'google', 'mixed')`);
        await queryRunner.query(`CREATE TYPE "public"."user_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('admin', 'moderator', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('active', 'banned', 'deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."user_subscription_tier_enum" AS ENUM('tier_1', 'tier_2')`);
        await queryRunner.query(`CREATE TYPE "public"."user_subscription_period_enum" AS ENUM('monthly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(15) NOT NULL, "nickname" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "googleId" character varying(255), "authProvider" "public"."user_auth_provider_enum" NOT NULL DEFAULT 'local', "profileImageUrl" text, "profileBackgroundImageUrl" text, "description" character varying(500), "gender" "public"."user_gender_enum", "usernameChangedAt" TIMESTAMP, "showAdultContent" boolean NOT NULL DEFAULT false, "adultContentConfirmedAt" TIMESTAMP, "termsAndPrivacyAcceptedAt" TIMESTAMP, "role" "public"."user_role_enum" NOT NULL DEFAULT 'user', "status" "public"."user_status_enum" NOT NULL DEFAULT 'active', "isVerified" boolean NOT NULL DEFAULT false, "premiumUntil" TIMESTAMP, "subscriptionTier" "public"."user_subscription_tier_enum", "subscriptionPeriod" "public"."user_subscription_period_enum", "refreshToken" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "lastGlobalNotificationSeenAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_470355432cc67b2c470c30bef7c" UNIQUE ("googleId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" SERIAL NOT NULL, "content" character varying(1500) NOT NULL, "isRecommend" boolean NOT NULL, "userId" uuid NOT NULL, "novelId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "likeCount" integer NOT NULL DEFAULT '0', "replyCount" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6b69a8d7e18953c44632335e7f" ON "comment" ("isRecommend") `);
        await queryRunner.query(`CREATE INDEX "IDX_9956996d3c70bccf568212322c" ON "comment" ("novelId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f5625635042bc0d9f6e8ed05de" ON "comment" ("userId", "novelId") `);
        await queryRunner.query(`CREATE TABLE "category" ("id" SERIAL NOT NULL, "title" character varying(30) NOT NULL, CONSTRAINT "UQ_9f16dbbf263b0af0f03637fa7b5" UNIQUE ("title"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f16dbbf263b0af0f03637fa7b" ON "category" ("title") `);
        await queryRunner.query(`CREATE TABLE "author" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nickname" character varying(50), "userId" uuid, "isVerified" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_645811deaaaa772f9e6c2a4b92" UNIQUE ("userId"), CONSTRAINT "PK_5a0e79799d372fe56f2f3fa6871" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_645811deaaaa772f9e6c2a4b92" ON "author" ("userId") `);
        await queryRunner.query(`CREATE TABLE "novel_daily_stats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "totalViews" integer NOT NULL, "totalReviews" integer NOT NULL, "totalPositiveReviews" integer NOT NULL, "totalLibraryCount" integer NOT NULL DEFAULT '0', "novelId" uuid NOT NULL, "recordedAt" date NOT NULL, CONSTRAINT "PK_0ce11044bd8f2685aeee54647b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."novel_status_enum" AS ENUM('ongoing', 'completed', 'hiatus', 'cancelled', 'draft')`);
        await queryRunner.query(`CREATE TYPE "public"."novel_type_enum" AS ENUM('CLASSIC', 'USER_GENERATED', 'WEB_NOVEL', 'LIGHT_NOVEL')`);
        await queryRunner.query(`CREATE TABLE "novel" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "slug" character varying(200) NOT NULL, "coverImage" text, "synopsis" character varying(1500), "status" "public"."novel_status_enum" NOT NULL DEFAULT 'draft', "type" "public"."novel_type_enum" NOT NULL DEFAULT 'USER_GENERATED', "free_limit" integer NOT NULL DEFAULT '0', "chapterCount" integer NOT NULL DEFAULT '0', "averageChapterWordCount" integer, "rankingScore" double precision NOT NULL DEFAULT '0', "lastChapterDate" TIMESTAMP, "bannedUntil" TIMESTAMP, "banReason" character varying(500), "isAdultContent" boolean NOT NULL DEFAULT false, "authorId" uuid NOT NULL, "viewCount" integer NOT NULL DEFAULT '0', "positiveReviewsCount" integer NOT NULL DEFAULT '0', "totalReviewsCount" integer NOT NULL DEFAULT '0', "totalLibraryCount" integer NOT NULL DEFAULT '0', "weeklyRankingScore" numeric(10,4) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_55d21d609055b4ba30d3355e4be" UNIQUE ("slug"), CONSTRAINT "PK_b0fea0838ae7d287445c53d6139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_838b9ff59b45444502d89d67bd" ON "novel" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_55d21d609055b4ba30d3355e4b" ON "novel" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_712932cdd8f2602d625b09da54" ON "novel" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_179a6a4ea945120174061e6ec7" ON "novel" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_novel_bannedUntil" ON "novel" ("bannedUntil") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b8dadc5fd88639952d78a37a1" ON "novel" ("authorId") `);
        await queryRunner.query(`CREATE TABLE "editor_pick" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "novelId" uuid NOT NULL, "orderIndex" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_332056acfc1b8e5b1c6fb8f50d4" UNIQUE ("novelId"), CONSTRAINT "PK_0b165e704d99ea4ad9034910eda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_editor_pick_novelId" ON "editor_pick" ("novelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2340ba58cdad067c9613cd6e33" ON "editor_pick" ("orderIndex") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae78b7fc3fd95a12a38c18628c" ON "editor_pick" ("isActive") `);
        await queryRunner.query(`CREATE TABLE "novel_weekly_rank_snapshot" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "novelId" uuid NOT NULL, "rankingScore" numeric(10,4) NOT NULL DEFAULT '0', "rank" integer NOT NULL, "recordedAt" date NOT NULL, CONSTRAINT "UQ_novel_weekly_rank_snapshot_novel_recorded" UNIQUE ("novelId", "recordedAt"), CONSTRAINT "PK_96a42f2de8b4a279de51ba7c5ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_085c3409fd1d68879645691be6" ON "novel_weekly_rank_snapshot" ("novelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2aea1f03623c300afd47f715c" ON "novel_weekly_rank_snapshot" ("recordedAt") `);
        await queryRunner.query(`CREATE TABLE "global_notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "summary" character varying(500) NOT NULL, "content" text, "targetUrl" text, "isPublished" boolean NOT NULL DEFAULT true, "publishedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3a5a16b5dc95e4a3d5287bdb37c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_read_chapter" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "novelId" uuid NOT NULL, "chapterId" uuid NOT NULL, CONSTRAINT "UQ_9e21ba6f05fd0d51d48ecd661cc" UNIQUE ("userId", "novelId", "chapterId"), CONSTRAINT "PK_99a25c43490e690cfa163cc4cf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_submission_type_enum" AS ENUM('support', 'feedback', 'suggestion', 'report', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_submission_status_enum" AS ENUM('pending', 'in_progress', 'resolved')`);
        await queryRunner.query(`CREATE TABLE "feedback_submission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "email" character varying(255), "type" "public"."feedback_submission_type_enum" NOT NULL, "status" "public"."feedback_submission_status_enum" NOT NULL DEFAULT 'pending', "subject" character varying(120) NOT NULL, "message" text NOT NULL, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b7ce399f9a506c8af4a7e94003c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "deleted_account_recovery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "emailHash" character(64) NOT NULL, "usernameHash" character(64) NOT NULL, "deletedAt" TIMESTAMP NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8e188fd4692b97c7d3ef1b7a0a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_663c6ce51b424953c8016503a6" ON "deleted_account_recovery" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2587ad31473018bd5dcb76a900" ON "deleted_account_recovery" ("expiresAt") `);
        await queryRunner.query(`CREATE TABLE "novel_categories" ("novelId" uuid NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_5d0edcc2bf14e7282a5fe6c9fc3" PRIMARY KEY ("novelId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_36b4683b24711ff72354bfc39a" ON "novel_categories" ("novelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f898c3dd408aea9e88f9e29b2" ON "novel_categories" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "novel_tags" ("novelId" uuid NOT NULL, "tagsId" uuid NOT NULL, CONSTRAINT "PK_283b116ff9695bfaede1a01fe6d" PRIMARY KEY ("novelId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91f6da8f0ae27c68fa8a8d3aed" ON "novel_tags" ("novelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_78de0d2660b0c800d4ed53caf7" ON "novel_tags" ("tagsId") `);
        await queryRunner.query(`ALTER TABLE "comment_like" ADD CONSTRAINT "FK_a253dba95eab8659c027bbace44" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_like" ADD CONSTRAINT "FK_b5a2fc7a9a2b6bcc8c74f6fbb8b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_e56de5f3dcb3c112de1e983b8e7" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "library" ADD CONSTRAINT "FK_60959da3c7fbc7f148fcbcbc9ea" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "library" ADD CONSTRAINT "FK_b274fe9a585d96364a64fd16df0" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_like" ADD CONSTRAINT "FK_1d39629a1cb60026550bf2d4eb2" FOREIGN KEY ("replyId") REFERENCES "reply"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply_like" ADD CONSTRAINT "FK_5dca5026905fe63fa7b24a3c353" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_e9886d6d04a19413a2f0aac5d7b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_f0af68fe0e599c7cc7f34699ad5" FOREIGN KEY ("parentReplyId") REFERENCES "reply"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reply" ADD CONSTRAINT "FK_9edaea29c2239e325a82f0b1e5e" FOREIGN KEY ("rootCommentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_verification" ADD CONSTRAINT "FK_b98835ab0c83f27ff7c4c7de3db" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "volume" ADD CONSTRAINT "FK_b771ca48dff4800e06603f1386e" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_publication" ADD CONSTRAINT "FK_78e86463cfafdcd4c32fe157548" FOREIGN KEY ("chapterId") REFERENCES "chapter"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_publication" ADD CONSTRAINT "FK_ea153c8dcac8d988aa604a3210b" FOREIGN KEY ("volumeId") REFERENCES "volume"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_comment_like" ADD CONSTRAINT "FK_b225f475d5abe8f8f8c6e061091" FOREIGN KEY ("commentId") REFERENCES "chapter_comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_comment_like" ADD CONSTRAINT "FK_a2502defc528b10987e6eda5f3a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" ADD CONSTRAINT "FK_08b9872601c18975a5457b636aa" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" ADD CONSTRAINT "FK_19f8d1d4ca007b137ddc9f99eab" FOREIGN KEY ("chapterId") REFERENCES "chapter"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" ADD CONSTRAINT "FK_cd9c3b0fbfc235c2f1dabc4306a" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" ADD CONSTRAINT "FK_2cb7f1685fc47a53576c358b383" FOREIGN KEY ("rootCommentId") REFERENCES "chapter_comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" ADD CONSTRAINT "FK_3c3c884dd6793362d9b06e9b400" FOREIGN KEY ("parentCommentId") REFERENCES "chapter_comment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter" ADD CONSTRAINT "FK_d047ff3ef628a3241aab6607247" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reading_stats" ADD CONSTRAINT "FK_114e9bc627fb432218d8db69455" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reading_stats" ADD CONSTRAINT "FK_72bc76c50a4862c50bd72a5afaf" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reading_stats" ADD CONSTRAINT "FK_809bf9a642ee14376f5041e6ff5" FOREIGN KEY ("lastReadChapterId", "novelId") REFERENCES "chapter"("id","novelId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal_notification" ADD CONSTRAINT "FK_9662ad991e6f135c1cfa43b82a4" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal_notification" ADD CONSTRAINT "FK_a44babada22eae999693895a99a" FOREIGN KEY ("actorUserId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_device" ADD CONSTRAINT "FK_bda1afb30d9e3e8fb30b1e90af7" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_follow" ADD CONSTRAINT "FK_5b43197da47affcac5c81422536" FOREIGN KEY ("followerId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_follow" ADD CONSTRAINT "FK_0892d05a7341b2b7abdf3da577d" FOREIGN KEY ("followingId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_block" ADD CONSTRAINT "FK_7eb0864a4303a6b9f8b2359fa0d" FOREIGN KEY ("blockerId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_block" ADD CONSTRAINT "FK_4e6b2dd464fda99399eb61855cb" FOREIGN KEY ("blockedId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset" ADD CONSTRAINT "FK_05baebe80e9f8fab8207eda250c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_c0354a9a009d3bb45a08655ce3b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_9956996d3c70bccf568212322c5" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "author" ADD CONSTRAINT "FK_645811deaaaa772f9e6c2a4b927" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "novel_daily_stats" ADD CONSTRAINT "FK_73c8e131b6b2ec65ab4d23fe0ce" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "novel" ADD CONSTRAINT "FK_9b8dadc5fd88639952d78a37a1f" FOREIGN KEY ("authorId") REFERENCES "author"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "editor_pick" ADD CONSTRAINT "FK_332056acfc1b8e5b1c6fb8f50d4" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "novel_weekly_rank_snapshot" ADD CONSTRAINT "FK_085c3409fd1d68879645691be60" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_read_chapter" ADD CONSTRAINT "FK_6a3a30a3a617e0d7ccfdf723ada" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_read_chapter" ADD CONSTRAINT "FK_a7343aec75306fbb4d87c250b89" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_read_chapter" ADD CONSTRAINT "FK_956d3d0ee6d22b5bdc3c8f51ff8" FOREIGN KEY ("chapterId", "novelId") REFERENCES "chapter"("id","novelId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback_submission" ADD CONSTRAINT "FK_19f59428e94ef68bb86dbd1d272" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "novel_categories" ADD CONSTRAINT "FK_36b4683b24711ff72354bfc39a7" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "novel_categories" ADD CONSTRAINT "FK_6f898c3dd408aea9e88f9e29b25" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "novel_tags" ADD CONSTRAINT "FK_91f6da8f0ae27c68fa8a8d3aedd" FOREIGN KEY ("novelId") REFERENCES "novel"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "novel_tags" ADD CONSTRAINT "FK_78de0d2660b0c800d4ed53caf73" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "novel_tags" DROP CONSTRAINT "FK_78de0d2660b0c800d4ed53caf73"`);
        await queryRunner.query(`ALTER TABLE "novel_tags" DROP CONSTRAINT "FK_91f6da8f0ae27c68fa8a8d3aedd"`);
        await queryRunner.query(`ALTER TABLE "novel_categories" DROP CONSTRAINT "FK_6f898c3dd408aea9e88f9e29b25"`);
        await queryRunner.query(`ALTER TABLE "novel_categories" DROP CONSTRAINT "FK_36b4683b24711ff72354bfc39a7"`);
        await queryRunner.query(`ALTER TABLE "feedback_submission" DROP CONSTRAINT "FK_19f59428e94ef68bb86dbd1d272"`);
        await queryRunner.query(`ALTER TABLE "user_read_chapter" DROP CONSTRAINT "FK_956d3d0ee6d22b5bdc3c8f51ff8"`);
        await queryRunner.query(`ALTER TABLE "user_read_chapter" DROP CONSTRAINT "FK_a7343aec75306fbb4d87c250b89"`);
        await queryRunner.query(`ALTER TABLE "user_read_chapter" DROP CONSTRAINT "FK_6a3a30a3a617e0d7ccfdf723ada"`);
        await queryRunner.query(`ALTER TABLE "novel_weekly_rank_snapshot" DROP CONSTRAINT "FK_085c3409fd1d68879645691be60"`);
        await queryRunner.query(`ALTER TABLE "editor_pick" DROP CONSTRAINT "FK_332056acfc1b8e5b1c6fb8f50d4"`);
        await queryRunner.query(`ALTER TABLE "novel" DROP CONSTRAINT "FK_9b8dadc5fd88639952d78a37a1f"`);
        await queryRunner.query(`ALTER TABLE "novel_daily_stats" DROP CONSTRAINT "FK_73c8e131b6b2ec65ab4d23fe0ce"`);
        await queryRunner.query(`ALTER TABLE "author" DROP CONSTRAINT "FK_645811deaaaa772f9e6c2a4b927"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_9956996d3c70bccf568212322c5"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_c0354a9a009d3bb45a08655ce3b"`);
        await queryRunner.query(`ALTER TABLE "password_reset" DROP CONSTRAINT "FK_05baebe80e9f8fab8207eda250c"`);
        await queryRunner.query(`ALTER TABLE "user_block" DROP CONSTRAINT "FK_4e6b2dd464fda99399eb61855cb"`);
        await queryRunner.query(`ALTER TABLE "user_block" DROP CONSTRAINT "FK_7eb0864a4303a6b9f8b2359fa0d"`);
        await queryRunner.query(`ALTER TABLE "user_follow" DROP CONSTRAINT "FK_0892d05a7341b2b7abdf3da577d"`);
        await queryRunner.query(`ALTER TABLE "user_follow" DROP CONSTRAINT "FK_5b43197da47affcac5c81422536"`);
        await queryRunner.query(`ALTER TABLE "user_device" DROP CONSTRAINT "FK_bda1afb30d9e3e8fb30b1e90af7"`);
        await queryRunner.query(`ALTER TABLE "personal_notification" DROP CONSTRAINT "FK_a44babada22eae999693895a99a"`);
        await queryRunner.query(`ALTER TABLE "personal_notification" DROP CONSTRAINT "FK_9662ad991e6f135c1cfa43b82a4"`);
        await queryRunner.query(`ALTER TABLE "reading_stats" DROP CONSTRAINT "FK_809bf9a642ee14376f5041e6ff5"`);
        await queryRunner.query(`ALTER TABLE "reading_stats" DROP CONSTRAINT "FK_72bc76c50a4862c50bd72a5afaf"`);
        await queryRunner.query(`ALTER TABLE "reading_stats" DROP CONSTRAINT "FK_114e9bc627fb432218d8db69455"`);
        await queryRunner.query(`ALTER TABLE "chapter" DROP CONSTRAINT "FK_d047ff3ef628a3241aab6607247"`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" DROP CONSTRAINT "FK_3c3c884dd6793362d9b06e9b400"`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" DROP CONSTRAINT "FK_2cb7f1685fc47a53576c358b383"`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" DROP CONSTRAINT "FK_cd9c3b0fbfc235c2f1dabc4306a"`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" DROP CONSTRAINT "FK_19f8d1d4ca007b137ddc9f99eab"`);
        await queryRunner.query(`ALTER TABLE "chapter_comment" DROP CONSTRAINT "FK_08b9872601c18975a5457b636aa"`);
        await queryRunner.query(`ALTER TABLE "chapter_comment_like" DROP CONSTRAINT "FK_a2502defc528b10987e6eda5f3a"`);
        await queryRunner.query(`ALTER TABLE "chapter_comment_like" DROP CONSTRAINT "FK_b225f475d5abe8f8f8c6e061091"`);
        await queryRunner.query(`ALTER TABLE "chapter_publication" DROP CONSTRAINT "FK_ea153c8dcac8d988aa604a3210b"`);
        await queryRunner.query(`ALTER TABLE "chapter_publication" DROP CONSTRAINT "FK_78e86463cfafdcd4c32fe157548"`);
        await queryRunner.query(`ALTER TABLE "volume" DROP CONSTRAINT "FK_b771ca48dff4800e06603f1386e"`);
        await queryRunner.query(`ALTER TABLE "user_verification" DROP CONSTRAINT "FK_b98835ab0c83f27ff7c4c7de3db"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_9edaea29c2239e325a82f0b1e5e"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_f0af68fe0e599c7cc7f34699ad5"`);
        await queryRunner.query(`ALTER TABLE "reply" DROP CONSTRAINT "FK_e9886d6d04a19413a2f0aac5d7b"`);
        await queryRunner.query(`ALTER TABLE "reply_like" DROP CONSTRAINT "FK_5dca5026905fe63fa7b24a3c353"`);
        await queryRunner.query(`ALTER TABLE "reply_like" DROP CONSTRAINT "FK_1d39629a1cb60026550bf2d4eb2"`);
        await queryRunner.query(`ALTER TABLE "library" DROP CONSTRAINT "FK_b274fe9a585d96364a64fd16df0"`);
        await queryRunner.query(`ALTER TABLE "library" DROP CONSTRAINT "FK_60959da3c7fbc7f148fcbcbc9ea"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_e56de5f3dcb3c112de1e983b8e7"`);
        await queryRunner.query(`ALTER TABLE "comment_like" DROP CONSTRAINT "FK_b5a2fc7a9a2b6bcc8c74f6fbb8b"`);
        await queryRunner.query(`ALTER TABLE "comment_like" DROP CONSTRAINT "FK_a253dba95eab8659c027bbace44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78de0d2660b0c800d4ed53caf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91f6da8f0ae27c68fa8a8d3aed"`);
        await queryRunner.query(`DROP TABLE "novel_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f898c3dd408aea9e88f9e29b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36b4683b24711ff72354bfc39a"`);
        await queryRunner.query(`DROP TABLE "novel_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2587ad31473018bd5dcb76a900"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_663c6ce51b424953c8016503a6"`);
        await queryRunner.query(`DROP TABLE "deleted_account_recovery"`);
        await queryRunner.query(`DROP TABLE "feedback_submission"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_submission_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_submission_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_read_chapter"`);
        await queryRunner.query(`DROP TABLE "global_notification"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2aea1f03623c300afd47f715c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_085c3409fd1d68879645691be6"`);
        await queryRunner.query(`DROP TABLE "novel_weekly_rank_snapshot"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae78b7fc3fd95a12a38c18628c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2340ba58cdad067c9613cd6e33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_editor_pick_novelId"`);
        await queryRunner.query(`DROP TABLE "editor_pick"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b8dadc5fd88639952d78a37a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_novel_bannedUntil"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_179a6a4ea945120174061e6ec7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_712932cdd8f2602d625b09da54"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55d21d609055b4ba30d3355e4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_838b9ff59b45444502d89d67bd"`);
        await queryRunner.query(`DROP TABLE "novel"`);
        await queryRunner.query(`DROP TYPE "public"."novel_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."novel_status_enum"`);
        await queryRunner.query(`DROP TABLE "novel_daily_stats"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_645811deaaaa772f9e6c2a4b92"`);
        await queryRunner.query(`DROP TABLE "author"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f16dbbf263b0af0f03637fa7b"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5625635042bc0d9f6e8ed05de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9956996d3c70bccf568212322c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b69a8d7e18953c44632335e7f"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_subscription_period_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_subscription_tier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_auth_provider_enum"`);
        await queryRunner.query(`DROP TABLE "password_reset"`);
        await queryRunner.query(`DROP TABLE "user_block"`);
        await queryRunner.query(`DROP TABLE "user_follow"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bcbc5516c8217e27beec37ab5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bda1afb30d9e3e8fb30b1e90af"`);
        await queryRunner.query(`DROP TABLE "user_device"`);
        await queryRunner.query(`DROP TYPE "public"."user_device_platform_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_device_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c52c9f6bd7af5281a6bfc5fde7"`);
        await queryRunner.query(`DROP TABLE "personal_notification"`);
        await queryRunner.query(`DROP TYPE "public"."personal_notification_targettype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."personal_notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "reading_stats"`);
        await queryRunner.query(`DROP TABLE "chapter"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c3c884dd6793362d9b06e9b40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cb7f1685fc47a53576c358b38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd9c3b0fbfc235c2f1dabc4306"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19f8d1d4ca007b137ddc9f99ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08b9872601c18975a5457b636a"`);
        await queryRunner.query(`DROP TABLE "chapter_comment"`);
        await queryRunner.query(`DROP TABLE "chapter_comment_like"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f6a9fe2a993304e22c38797a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30b15da7bd56c635a402b59874"`);
        await queryRunner.query(`DROP TABLE "chapter_publication"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b8c8af0bba587b76864d0eee"`);
        await queryRunner.query(`DROP TABLE "volume"`);
        await queryRunner.query(`DROP TABLE "user_verification"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9edaea29c2239e325a82f0b1e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0af68fe0e599c7cc7f34699ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9886d6d04a19413a2f0aac5d7"`);
        await queryRunner.query(`DROP TABLE "reply"`);
        await queryRunner.query(`DROP TABLE "reply_like"`);
        await queryRunner.query(`DROP TABLE "library"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3aa10c29ea4e61a830362bd25"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "comment_like"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10e84f71d01bc582941849169e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b77505eb57ce82f8d74bdfa17c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccaf837f12d98370d46f100bcb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_efa05d22002077f5c4705d4c21"`);
        await queryRunner.query(`DROP TABLE "banner"`);
        await queryRunner.query(`DROP TYPE "public"."banner_targettype_enum"`);
    }

}
