export const mockUsers = [
  {
    username: "auroofnine",
    nickname: "Auro of Nine",
    email: "emircanemre09@gmail.com",
    password: "emircan2004",
    profileImageUrl: "https://avatars.githubusercontent.com/u/109489441?v=4",
    description: "Full-stack developer and coffee enthusiast.",
  },
  {
    username: "jackshepard",
    nickname: "Jack Shepheard",
    email: "jack_shepheard@gmail.com",
    password: "randompassword",
    profileImageUrl: "https://i.pravatar.cc/150?u=jack",
    description: "We have to go back!",
  },
  {
    username: "daenerys_t",
    nickname: "Dragon Mother",
    email: "khaleesi@westeros.com",
    password: "dracarys_123",
    profileImageUrl: "https://i.pravatar.cc/150?u=dragon",
    description: "Breaker of Chains and Mother of Dragons.",
  },
  {
    username: "tonystark",
    nickname: "Iron Man",
    email: "tony@starkindustries.com",
    password: "iloveyou3000",
    profileImageUrl: "https://i.pravatar.cc/150?u=stark",
    description: "Genius, billionaire, playboy, philanthropist.",
  },
  {
    username: "walterwhite",
    nickname: "Heisenberg",
    email: "ww@bluecrystal.com",
    password: "iamtheone_who_knocks",
    profileImageUrl: "https://i.pravatar.cc/150?u=walter",
    description: "I am the one who knocks!",
  },
  {
    username: "cyberpunk2077",
    nickname: "V",
    email: "v@nightcity.io",
    password: "wake-up-samurai",
    profileImageUrl: "https://i.pravatar.cc/150?u=cyber",
    description: "Just a merc trying to survive in Night City.",
  },
  {
    username: "detective_l",
    nickname: "L",
    email: "l_lawliet@wammys.com",
    password: "justice_prevails",
    profileImageUrl: "https://i.pravatar.cc/150?u=detective",
    description: "Justice will prevail, no matter what.",
  },
  {
    username: "neo_matrix",
    nickname: "The One",
    email: "anderson@neb.net",
    password: "there_is_no_spoon",
    profileImageUrl: "https://i.pravatar.cc/150?u=neo",
    description: "I know kung-fu.",
  },
  {
    username: "geralt_of_rivia",
    nickname: "White Wolf",
    email: "geralt@kaermorhen.com",
    password: "toss_a_coin_2026",
    profileImageUrl: "https://i.pravatar.cc/150?u=witcher",
    description: "Looking for monsters and Gwent players.",
  },
  {
    username: "ellie_w",
    nickname: "The Last One",
    email: "ellie@fireflies.org",
    password: "endure_and_survive",
    profileImageUrl: "https://i.pravatar.cc/150?u=ellie",
    description: "Endure and survive.",
  },
];

export const mockCategories = [
  { enName: "Romance", trName: "Romantizm" },
  { enName: "Science Fiction", trName: "Bilim Kurgu" },
  { enName: "Action", trName: "Aksiyon" },
  { enName: "Adventure", trName: "Macera" },
  { enName: "Comedy", trName: "Komedi" },
  { enName: "Drama", trName: "Drama" },
  { enName: "Horror", trName: "Korku" },
  { enName: "Mystery", trName: "Gizem" },
  { enName: "Thriller", trName: "Gerilim" },
  { enName: "Fantasy", trName: "Fantastik" },
  { enName: "Animation", trName: "Animasyon" },
  { enName: "Documentary", trName: "Belgesel" },
  { enName: "Biography", trName: "Biyografi" },
  { enName: "History", trName: "Tarih" },
  { enName: "Musical", trName: "Müzikal" },
  { enName: "Crime", trName: "Suç" },
  { enName: "Family", trName: "Aile" },
  { enName: "Psychology", trName: "Psikoloji" },
  { enName: "Sport", trName: "Spor" },
  { enName: "Western", trName: "Vahşi Batı" },
];
