import { IAuthorRepository } from "./author.repo.interface.js";
import { ICategoryRepository } from "./categories.repo.interface.js";
import { IChapterPublicationRepository } from "./chapter.publication.repo.interface.js";
import { IChapterCommentLikeRepository } from "./chapter.comment.like.repo.interface.js";
import { IChapterCommentRepository } from "./chapter.comment.repo.interface.js";
import { IChapterRepository } from "./chapter.repo.interface.js";
import { ICommentLikeRepository } from "./comment.like.repo.interface.js";
import { ICommentRepository } from "./comment.repo.interface.js";
import { ILibraryRepository } from "./library.repo.interface.js";
import { INovelDailyStatsRepository } from "./novel.daily.stats.repo.interface.js";
import { INovelRepository } from "./novel.repo.interface.js";
import { IReplyLikeRepository } from "./reply.like.repo.interface.js";
import { IReplyRepository } from "./reply.repo.interface.js";
import { ITagRepository } from "./tag.repo.interface.js";
import { IUserRepository } from "./user.repo.interface.js";
import { IUserVerificationRepository } from "./user.verification.repo.interface.js";
import { IVolumeRepository } from "./volume.repo.interface.js";
import { IReadingStatsRepository } from "./reading.stats.repository.interface.js";
import { IPersonalNotificationRepository } from "./personal.notification.repo.interface.js";
import { IGlobalNotificationRepository } from "./global.notification.repo.interface.js";
import { IUserDeviceRepository } from "./user.device.repo.interface.js";
import { IUserFollowRepository } from "./user.follow.repo.interface.js";
import { IUserBlockRepository } from "./user.block.repo.interface.js";
import { IUserReadChapterRepository } from "./user.read.chapter.repo.interface.js";
import { IPasswordResetRepository } from "./password.reset.repo.interface.js";
import { IFeedbackSubmissionRepository } from "./feedback.submission.repo.interface.js";
import { IBannerRepository } from "./banner.repo.interface.js";

export interface IUnitOfWork {
  authorRepository: IAuthorRepository;
  categoryRepository: ICategoryRepository;
  chapterRepository: IChapterRepository;
  chapterCommentRepository: IChapterCommentRepository;
  chapterCommentLikeRepository: IChapterCommentLikeRepository;
  chapterPublicationRepository: IChapterPublicationRepository;
  commentRepository: ICommentRepository;
  commentLikeRepository: ICommentLikeRepository;
  libraryRepository: ILibraryRepository;
  novelRepository: INovelRepository;
  novelDailyStatsRepository: INovelDailyStatsRepository;
  replyRepository: IReplyRepository;
  replyLikeRepository: IReplyLikeRepository;
  tagRepository: ITagRepository;
  userRepository: IUserRepository;
  userVerificationRepository: IUserVerificationRepository;
  volumeRepository: IVolumeRepository;
  readingStatsRepository: IReadingStatsRepository;
  personalNotificationRepository: IPersonalNotificationRepository;
  globalNotificationRepository: IGlobalNotificationRepository;
  userDeviceRepository: IUserDeviceRepository;
  userFollowRepository: IUserFollowRepository;
  userBlockRepository: IUserBlockRepository;
  userReadChapterRepository: IUserReadChapterRepository;
  passwordResetRepository: IPasswordResetRepository;
  feedbackSubmissionRepository: IFeedbackSubmissionRepository;
  bannerRepository: IBannerRepository;

  startTransaction(): Promise<void>;
  commit(): Promise<void>;
  rollback(): Promise<void>;
  release(): Promise<void>;
}
